# Generated by Django 5.0.4 on 2024-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
